###
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "email": "test5@naver.com",
  "userName": "test2",
  "password": "1234",
  "passwordConfirm": "1234",
  "roles": ""
}

###
GET http://localhost:8080/api/member?email=test@naver.com


###
POST http://localhost:8080/api/member/signin
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "1234"
}

###
PUT http://localhost:8080/api/member/update
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG5hdmVyLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3MjE1MjUzMjEsImV4cCI6MTcyMTUyODkyMX0.F6s13fBB6hJKFXjzmELhWs07QMJ8gwHPMEEUgByMMLs

{
  "email": "test@naver.com",
  "userName": "test55"
}

###
PATCH http://localhost:8080/api/member/update/password
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG5hdmVyLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3MjE1MjUzMjEsImV4cCI6MTcyMTUyODkyMX0.F6s13fBB6hJKFXjzmELhWs07QMJ8gwHPMEEUgByMMLs

{
  "email": "test@naver.com",
  "password": "1234",
  "newPassword": "12345",
  "newPasswordConfirm": "12345"
}

###
DELETE http://localhost:8080/api/member/delete
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0NUBuYXZlci5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIxNTIxODU5LCJleHAiOjE3MjE1MjU0NTl9.oyEUBJpndwHobYLFeZt2RUnywtV2BLJRnKKoY088Yi4

{
  "email": "test5@naver.com",
  "password": "12345"
}