###
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "email": "test2@naver.com",
  "userName": "test",
  "password": "1234",
  "passwordConfirm": "1234"
}

###
GET http://localhost:8080/api/member
Content-Type: application/json

{
  "email": "test@naver.com"
}

###
POST http://localhost:8080/api/member/signin
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "1234"
}

###
PUT http://localhost:8080/api/member/update
Content-Type: application/json

{
  "email": "test@naver.com",
  "userName": "test1"
}

###
PATCH http://localhost:8080/api/member/update/password
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "1234",
  "newPassword": "12345",
  "newPasswordConfirm": "12345"
}

###
DELETE http://localhost:8080/api/member/delete
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBuYXZlci5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIxMzMxOTA5LCJleHAiOjE3MjEzMzU1MDl9.5aVsU0nI3XHrBRQJIzylN5djXFFpSKmYQA5PNcMkcnU

{
  "email": "test2@naver.com",
  "password": "1234"
}