###
POST http://localhost:8080/api/post
Content-Type: application/json

{
  "category": "IT",
  "title": "제목1",
  "contents": "내용1"
}

###
GET http://localhost:8080/api/post/1

###
PUT http://localhost:8080/api/post/1
Content-Type: application/json

{
  "category" : "게임",
  "title" : "제목2",
  "contents": "내용2"
}

###
DELETE http://localhost:8080/api/post/1


// User
###
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
  "email": "test@naver.com",
  "userName": "test",
  "password": "1234",
  "passwordConfirm": "1234"
}

###
GET http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "test@naver.com"
}

###
POST http://localhost:8080/api/user/signin
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "12345"
}

###
PUT http://localhost:8080/api/user/update
Content-Type: application/json

{
  "email": "test@naver.com",
  "userName": "test1"
}

###
PATCH http://localhost:8080/api/user/update/password
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "1234",
  "newPassword": "12345",
  "newPasswordConfirm": "12345"
}