spring:
  application:
    name: daits

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daits?serverTimezone=UTC&characterEncording=UTF-8
    username: root
    password: ghdnjs20215!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    show-sql: true
    database: mysql

  jwt:
    secret: daits