###
POST http://localhost:8080/api/comment/create/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG5hdmVyLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3MjE2MjMyNzAsImV4cCI6MTcyMTYyNjg3MH0.eidYBX347UXj3IcYzkkiMMWV-gwalGTFJloUVMp0ssQ

{
  "contents": "댓글4"
}

###
GET http://localhost:8080/api/comment/1/3

###
GET http://localhost:8080/api/comment/1

###
PATCH http://localhost:8080/api/comment/update/1/3
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG5hdmVyLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3MjE2MjMyNzAsImV4cCI6MTcyMTYyNjg3MH0.eidYBX347UXj3IcYzkkiMMWV-gwalGTFJloUVMp0ssQ

{
  "contents": "댓글수정2"
}

###
DELETE http://localhost:8080/api/comment/1/3/delete
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG5hdmVyLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3MjE2MjE3MTksImV4cCI6MTcyMTYyNTMxOX0.MdsohuLr0OWKY7TGEbPScapFPpFS8cJN2RxzSRb6o-c

###
POST http://localhost:8080/api/comment/recommend/1/3
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG5hdmVyLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3MjE2MjMyNzAsImV4cCI6MTcyMTYyNjg3MH0.eidYBX347UXj3IcYzkkiMMWV-gwalGTFJloUVMp0ssQ