###
POST http://localhost:8080/api/post/create
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG5hdmVyLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3MjE1MjUzMjEsImV4cCI6MTcyMTUyODkyMX0.F6s13fBB6hJKFXjzmELhWs07QMJ8gwHPMEEUgByMMLs

{
  "category": "IT",
  "title": "제목테스트2",
  "contents": "내용테스트2"
}

###
GET http://localhost:8080/api/post/6

###
PUT http://localhost:8080/api/post/update/6
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0NUBuYXZlci5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIxNTIxODU5LCJleHAiOjE3MjE1MjU0NTl9.oyEUBJpndwHobYLFeZt2RUnywtV2BLJRnKKoY088Yi4

{
  "category" : "게임",
  "title" : "제목수정테스트1",
  "contents": "내용수정테스트1"
}

###
DELETE http://localhost:8080/api/post/delete/6
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0NUBuYXZlci5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIxNTIxODU5LCJleHAiOjE3MjE1MjU0NTl9.oyEUBJpndwHobYLFeZt2RUnywtV2BLJRnKKoY088Yi4

###
POST http://localhost:8080/api/post/recommend/6
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0NUBuYXZlci5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIxNTIxODU5LCJleHAiOjE3MjE1MjU0NTl9.oyEUBJpndwHobYLFeZt2RUnywtV2BLJRnKKoY088Yi4

###
POST http://localhost:8080/api/post/notrecommend/6
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0NUBuYXZlci5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIxNTIxODU5LCJleHAiOjE3MjE1MjU0NTl9.oyEUBJpndwHobYLFeZt2RUnywtV2BLJRnKKoY088Yi4

###
GET http://localhost:8080/api/post/search?keyword=내용테스트&type=titleOrContents
