###
POST http://localhost:8080/api/post/create
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBuYXZlci5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIxMjUxNDA1LCJleHAiOjE3MjEyNTUwMDV9.P8rHrKwcE35Hp4fWA3R7WpZQ2l9zKcQp5QES7NoVilI

{
  "category": "IT",
  "title": "제목3",
  "contents": "내용3"
}

###
GET http://localhost:8080/api/post/1

###
PUT http://localhost:8080/api/post/update/3
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBuYXZlci5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIxMjUxNDA1LCJleHAiOjE3MjEyNTUwMDV9.P8rHrKwcE35Hp4fWA3R7WpZQ2l9zKcQp5QES7NoVilI

{
  "category" : "게임",
  "title" : "제목3",
  "contents": "내용3"
}

###
DELETE http://localhost:8080/api/post/delete/3
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MkBuYXZlci5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIxMjUxNDA1LCJleHAiOjE3MjEyNTUwMDV9.P8rHrKwcE35Hp4fWA3R7WpZQ2l9zKcQp5QES7NoVilI